
//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////
#define RunUo2_0

using System;
using Server;
using Server.Gumps;
using Server.Network;
using Server.Commands;

namespace Server.Gumps
{
    public class DonationChestGump : Gump
    {
        public DonationChestGump()
            : base(0, 0)
        {
            this.Closable=true;
			this.Disposable=true;
			this.Dragable=true;
			this.Resizable=false;

			AddPage(0);
			AddBackground(0, 40, 475, 313, 2600);
			AddImage(123, 18, 1419);
			AddImage(200, 0, 1417);
			AddImage(209, 9, 9012);
			AddBackground(50, 85, 374, 224, 9270);
			AddBackground(63, 96, 349, 200, 9200);
            AddHtml(66, 102, 341, 187, "This donation chest has been created and placed here in recognition of the musician inRed.  The staff at Ultima Online: Forever are extremely grateful for his contribution to the UOF community.<br><br>To listen to the new UOF theme song, click here: <a href=\"theme.uoforever.com\">Ultima Online: Forever Theme</a><br><br>You can view inRed's other work here: <a href=\"inredmusic.com\">inRed Music</a>.<br><br>You may donate gold, bank checks and donation coins in this chest to inRed.  To donate, drag one of the listed items onto this donation chest.", (bool)false, (bool)true);
			AddLabel(54, 67, 0, @"A Donation Chest");  
        }

        

        public override void OnResponse(NetState sender, RelayInfo info)
        {
            Mobile from = sender.Mobile;

            switch(info.ButtonID)
            {
                				case 0:
				{

					break;
				}

            }
        }
    }
}