
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class shadowsmithAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new shadowsmithAddonDeed();
			}
		}

		[ Constructable ]
		public shadowsmithAddon()
		{



			AddComplexComponent( (BaseAddon) this, 3648, -11, -2, 13, 1175, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3648, -11, -1, 13, 1175, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 4014, -11, 2, 7, 1175, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 4014, -11, 3, 7, 1175, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4014, -11, 3, 14, 1175, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7955, -9, -2, 7, 0, -1, "PremiumSpawner", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3015, 11, 2, 0, 1102, -1, "", 1);// 7

		}

		public shadowsmithAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class shadowsmithAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new shadowsmithAddon();
			}
		}

		[Constructable]
		public shadowsmithAddonDeed()
		{
			Name = "shadowsmith";
		}

		public shadowsmithAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}