
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class townfountainAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3472, -1, 2, 0}, {3472, 0, 2, 0}, {3433, 2, 1, 0}// 1	 2	 3	 
			, {3473, 2, 2, 0}, {3433, 2, -1, 0}, {3433, 2, 0, 0}// 4	 5	 6	 
			, {5719, 0, 0, 11}, {3380, -2, 1, 0}, {3424, 2, -2, 0}// 7	 8	 9	 
			, {3380, -2, -1, 0}, {3380, -2, 0, 0}, {3472, 1, 2, 0}// 10	 11	 12	 
			, {3376, -2, -2, 0}, {3423, -1, -2, 0}, {3423, 0, -2, 0}// 13	 14	 15	 
			, {3423, 1, -2, 0}, {3505, -2, 2, 0}// 16	 17	 
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new townfountainAddonDeed();
			}
		}

		[ Constructable ]
		public townfountainAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public townfountainAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class townfountainAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new townfountainAddon();
			}
		}

		[Constructable]
		public townfountainAddonDeed()
		{
			Name = "townfountain";
		}

		public townfountainAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}