
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class RoseRugNorthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {14509, 1, 1, 0}, {14502, -1, 0, 0}, {14516, 2, -1, 0}// 1	2	3	
			, {14506, 0, 0, 0}, {14517, 3, 1, 0}, {14498, -2, 1, 0}// 4	5	6	
			, {14504, -1, -1, 0}, {14499, -2, 0, 0}, {14513, 2, 1, 0}// 7	8	9	
			, {14514, 2, 0, 0}, {14518, -1, 1, 0}, {14508, 0, -1, 0}// 10	11	12	
			, {14501, 3, 0, 0}, {14505, 0, 1, 0}, {14510, 1, 0, 0}// 13	14	15	
			, {14512, 1, -1, 0}, {14520, 3, -1, 0}, {14500, -2, -1, 0}// 16	17	18	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new RoseRugNorthAddonDeed();
			}
		}

		[ Constructable ]
		public RoseRugNorthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public RoseRugNorthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class RoseRugNorthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new RoseRugNorthAddon();
			}
		}

		[Constructable]
		public RoseRugNorthAddonDeed()
		{
			Name = "RoseRugNorth";
		}

		public RoseRugNorthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}