// Automatically generated by the
// AddonGenerator script by Arya
// Generator edited 10.Mar.07 by Papler
using System;
using Server;
using Server.Items;
namespace Server.Items
{
	public class CrossWhiteSAddon : BaseAddon {
		public override BaseAddonDeed Deed{get{return new CrossWhiteSAddonDeed();}}
		[ Constructable ]
		public CrossWhiteSAddon()
		{
			CrossAddonComponent ac = null;
			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, -2, 0, 35 );

			ac = new CrossAddonComponent( 1812 );
			ac.Hue = 1150;
			AddComponent( ac, -2, 2, 0 );

			ac = new CrossAddonComponent( 1810 );
			ac.Hue = 1150;
			AddComponent( ac, -2, -2, 0 );

			ac = new CrossAddonComponent( 1805 );
			ac.Hue = 1150;
			AddComponent( ac, -2, 1, 0 );

			ac = new CrossAddonComponent( 1805 );
			ac.Hue = 1150;
			AddComponent( ac, -2, 0, 0 );

			ac = new CrossAddonComponent( 1805 );
			ac.Hue = 1150;
			AddComponent( ac, -2, -1, 0 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 45 );

			ac = new CrossAddonComponent( 3223 );
			AddComponent( ac, -1, 0, 6 );

			ac = new CrossAddonComponent( 3223 );
			AddComponent( ac, 0, -1, 5 );

			ac = new CrossAddonComponent( 3223 );
			AddComponent( ac, 1, 0, 5 );

			ac = new CrossAddonComponent( 3223 );
			AddComponent( ac, 0, 1, 5 );

			ac = new CrossAddonComponent( 4845 );
			ac.Hue = 20;
			AddComponent( ac, 3, 2, 31 );

			ac = new CrossAddonComponent( 4845 );
			ac.Hue = 20;
			AddComponent( ac, 0, 1, 20 );

			ac = new CrossAddonComponent( 11514 );
			AddComponent( ac, 1, 1, 13 );

			ac = new CrossAddonComponent( 11514 );
			AddComponent( ac, 1, 1, 25 );

			ac = new CrossAddonComponent( 3203 );
			ac.Hue = 20;
			AddComponent( ac, 1, -1, 5 );

			ac = new CrossAddonComponent( 3203 );
			ac.Hue = 20;
			AddComponent( ac, -1, 1, 5 );

			ac = new CrossAddonComponent( 3203 );
			ac.Hue = 20;
			AddComponent( ac, -1, -1, 5 );

			ac = new CrossAddonComponent( 3203 );
			ac.Hue = 20;
			AddComponent( ac, 1, 1, 5 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 40 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 35 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 30 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 0, 35 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, -1, 0, 35 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 2, 0, 35 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 25 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 20 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 15 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 10 );

			ac = new CrossAddonComponent( 1813 );
			ac.Hue = 1150;
			AddComponent( ac, 2, -2, 0 );

			ac = new CrossAddonComponent( 1811 );
			ac.Hue = 1150;
			AddComponent( ac, 2, 2, 0 );

			ac = new CrossAddonComponent( 1804 );
			ac.Hue = 1150;
			AddComponent( ac, 1, -2, 0 );

			ac = new CrossAddonComponent( 1804 );
			ac.Hue = 1150;
			AddComponent( ac, 0, -2, 0 );

			ac = new CrossAddonComponent( 1804 );
			ac.Hue = 1150;
			AddComponent( ac, -1, -2, 0 );

			ac = new CrossAddonComponent( 1803 );
			ac.Hue = 1150;
			AddComponent( ac, 2, 1, 0 );

			ac = new CrossAddonComponent( 1803 );
			ac.Hue = 1150;
			AddComponent( ac, 2, 0, 0 );

			ac = new CrossAddonComponent( 1803 );
			ac.Hue = 1150;
			AddComponent( ac, 2, -1, 0 );

			ac = new CrossAddonComponent( 1802 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 2, 0 );

			ac = new CrossAddonComponent( 1802 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 2, 0 );

			ac = new CrossAddonComponent( 1802 );
			ac.Hue = 1150;
			AddComponent( ac, -1, 2, 0 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 5 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 1, 0 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 1, 0, 0 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 1, -1, 0 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 1, 0 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 0, 0 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, 0, -1, 0 );

            ac = new CrossAddonComponent(1801);
			ac.Hue = 1150;
			AddComponent( ac, -1, 1, 0 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, -1, 0, 0 );

			ac = new CrossAddonComponent( 1801 );
			ac.Hue = 1150;
			AddComponent( ac, -1, -1, 0 );


		}
		public CrossWhiteSAddon( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){base.Serialize( writer );writer.Write( 0 );}
		public override void Deserialize( GenericReader reader ){base.Deserialize( reader );reader.ReadInt();}
	}

	public class CrossWhiteSAddonDeed : BaseAddonDeed {
		public override BaseAddon Addon{get{return new CrossWhiteSAddon();}}
		[Constructable]
		public CrossWhiteSAddonDeed(){Name = "CrossWhiteS";}
		public CrossWhiteSAddonDeed( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){	base.Serialize( writer );writer.Write( 0 );}
		public override void	Deserialize( GenericReader reader )	{base.Deserialize( reader );reader.ReadInt();}
	}
}