//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////

#define RunUo2_0

#region References

using Server.Items;
using Server.Network;

#endregion

namespace Server.Gumps
{
    public class RedeedHousetoHouseGump : Gump
    {
        private HouseToHouseTeleporter _H2HTeleporter;

        public RedeedHousetoHouseGump(HouseToHouseTeleporter teleporter)
            : base(0, 0)
        {
            Closable = true;
            Disposable = true;
            Dragable = true;
            Resizable = false;

            _H2HTeleporter = teleporter;

            AddPage(0);
            AddBackground(0, 0, 311, 105, 9270);
            AddBackground(13, 12, 286, 80, 9200);
            AddLabel(23, 17, 0, @"Would you like to redeed your teleporters?");
            AddButton(126, 57, 247, 248, 1, GumpButtonType.Reply, 0);
        }


        public override void OnResponse(NetState sender, RelayInfo info)
        {
            Mobile from = sender.Mobile;

            switch (info.ButtonID)
            {
                case 1:
                {
                    _H2HTeleporter.Redeed();
                    break;
                }
            }
        }
    }
}