////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////

namespace Server.Items
{
    public class PolarExpressCabooseAddon : BaseAddon
    {
        private static int[,] m_AddOnSimpleComponents =
        {
            {5534, -1, 1, 12}, {5534, -1, -1, 11}, {5534, -1, -3, 11} // 136	137	138	
            , {5534, -1, 3, 13} // 173	
        };


        public override BaseAddonDeed Deed { get { return new PolarExpressCabooseAddonDeed(); } }

        [Constructable]
        public PolarExpressCabooseAddon()
        {
            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
            {
                AddComponent(new AddonComponent(m_AddOnSimpleComponents[i, 0]), m_AddOnSimpleComponents[i, 1],
                    m_AddOnSimpleComponents[i, 2], m_AddOnSimpleComponents[i, 3]);
            }


            AddComplexComponent(this, 5718, 2, -1, 7, 1102, -1, "Polar Express Caboose", 1); // 1
            AddComplexComponent(this, 5718, 2, -2, 7, 1102, -1, "Polar Express Caboose", 1); // 2
            AddComplexComponent(this, 1981, 1, 1, 6, 1108, -1, "Polar Express Caboose", 1); // 3
            AddComplexComponent(this, 1981, 1, -1, 6, 1108, -1, "Polar Express Caboose", 1); // 4
            AddComplexComponent(this, 1981, 1, 0, 6, 1108, -1, "Polar Express Caboose", 1); // 5
            AddComplexComponent(this, 1981, 1, -2, 6, 1108, -1, "Polar Express Caboose", 1); // 6
            AddComplexComponent(this, 1981, 0, 1, 6, 1108, -1, "Polar Express Caboose", 1); // 7
            AddComplexComponent(this, 1981, 0, 0, 6, 1108, -1, "Polar Express Caboose", 1); // 8
            AddComplexComponent(this, 1981, 0, -1, 6, 1108, -1, "Polar Express Caboose", 1); // 9
            AddComplexComponent(this, 1981, 0, -2, 6, 1108, -1, "Polar Express Caboose", 1); // 10
            AddComplexComponent(this, 1981, -1, 1, 6, 1108, -1, "Polar Express Caboose", 1); // 11
            AddComplexComponent(this, 1981, -1, 0, 6, 1108, -1, "Polar Express Caboose", 1); // 12
            AddComplexComponent(this, 1981, -1, -1, 6, 1108, -1, "Polar Express Caboose", 1); // 13
            AddComplexComponent(this, 1981, -1, -2, 6, 1108, -1, "Polar Express Caboose", 1); // 14
            AddComplexComponent(this, 5718, 2, 2, 7, 1102, -1, "Polar Express Caboose", 1); // 15
            AddComplexComponent(this, 1981, -1, 2, 6, 1108, -1, "Polar Express Caboose", 1); // 16
            AddComplexComponent(this, 1981, 1, 2, 6, 1108, -1, "Polar Express Caboose", 1); // 17
            AddComplexComponent(this, 1981, 0, 2, 6, 1108, -1, "Polar Express Caboose", 1); // 18
            AddComplexComponent(this, 2170, 2, 0, 6, 2101, -1, "Polar Express Caboose", 1); // 19
            AddComplexComponent(this, 1981, 1, -3, 6, 1108, -1, "Polar Express Caboose", 1); // 20
            AddComplexComponent(this, 1981, 0, -3, 6, 1108, -1, "Polar Express Caboose", 1); // 21
            AddComplexComponent(this, 1981, -1, -3, 6, 1108, -1, "Polar Express Caboose", 1); // 22
            AddComplexComponent(this, 11584, -2, -3, 8, 33, -1, "Polar Express Caboose", 1); // 23
            AddComplexComponent(this, 11584, 1, -3, 8, 33, -1, "Polar Express Caboose", 1); // 24
            AddComplexComponent(this, 11585, 1, -4, 8, 33, -1, "Polar Express Caboose", 1); // 25
            AddComplexComponent(this, 11585, -1, -4, 8, 33, -1, "Polar Express Caboose", 1); // 26
            AddComplexComponent(this, 11549, -2, -4, 8, 33, -1, "Polar Express Caboose", 1); // 27
            AddComplexComponent(this, 1981, 1, -4, 6, 1108, -1, "Polar Express Caboose", 1); // 28
            AddComplexComponent(this, 1981, 0, -4, 6, 1108, -1, "Polar Express Caboose", 1); // 29
            AddComplexComponent(this, 1981, -1, -4, 6, 1108, -1, "Polar Express Caboose", 1); // 30
            AddComplexComponent(this, 2143, 1, -5, 8, 33, -1, "Polar Express Caboose", 1); // 31
            AddComplexComponent(this, 2143, -2, -5, 8, 33, -1, "Polar Express Caboose", 1); // 32
            AddComplexComponent(this, 2145, 1, -4, 8, 33, -1, "Polar Express Caboose", 1); // 33
            AddComplexComponent(this, 2145, -2, -4, 8, 33, -1, "Polar Express Caboose", 1); // 34
            AddComplexComponent(this, 2144, -1, -5, 8, 33, -1, "Polar Express Caboose", 1); // 35
            AddComplexComponent(this, 2144, 0, -5, 8, 33, -1, "Polar Express Caboose", 1); // 36
            AddComplexComponent(this, 2144, 1, -5, 8, 33, -1, "Polar Express Caboose", 1); // 37
            AddComplexComponent(this, 11582, 1, -2, 8, 33, -1, "Polar Express Caboose", 1); // 38
            AddComplexComponent(this, 11582, 1, 2, 8, 33, -1, "Polar Express Caboose", 1); // 39
            AddComplexComponent(this, 11582, -2, -2, 8, 33, -1, "Polar Express Caboose", 1); // 40
            AddComplexComponent(this, 11582, -2, 2, 8, 33, -1, "Polar Express Caboose", 1); // 41
            AddComplexComponent(this, 11584, -2, 0, 8, 33, -1, "Polar Express Caboose", 1); // 42
            AddComplexComponent(this, 11584, -2, 1, 8, 33, -1, "Polar Express Caboose", 1); // 43
            AddComplexComponent(this, 11584, 1, -1, 8, 33, -1, "Polar Express Caboose", 1); // 44
            AddComplexComponent(this, 11584, 1, 1, 8, 33, -1, "Polar Express Caboose", 1); // 45
            AddComplexComponent(this, 11584, -2, -1, 8, 33, -1, "Polar Express Caboose", 1); // 46
            AddComplexComponent(this, 1981, -1, -3, 28, 1368, -1, "Polar Express Caboose", 1); // 47
            AddComplexComponent(this, 1981, -1, -2, 28, 1368, -1, "Polar Express Caboose", 1); // 48
            AddComplexComponent(this, 1981, -1, -1, 28, 1368, -1, "Polar Express Caboose", 1); // 49
            AddComplexComponent(this, 1981, -1, 0, 28, 1368, -1, "Polar Express Caboose", 1); // 50
            AddComplexComponent(this, 1981, -1, 2, 28, 1368, -1, "Polar Express Caboose", 1); // 51
            AddComplexComponent(this, 1981, 0, -3, 28, 1368, -1, "Polar Express Caboose", 1); // 52
            AddComplexComponent(this, 1981, 0, -2, 28, 1368, -1, "Polar Express Caboose", 1); // 53
            AddComplexComponent(this, 1981, 0, -1, 28, 1368, -1, "Polar Express Caboose", 1); // 54
            AddComplexComponent(this, 1981, 0, 0, 28, 1368, -1, "Polar Express Caboose", 1); // 55
            AddComplexComponent(this, 1981, 0, 2, 28, 1368, -1, "Polar Express Caboose", 1); // 56
            AddComplexComponent(this, 1981, 1, -3, 28, 1368, -1, "Polar Express Caboose", 1); // 57
            AddComplexComponent(this, 1981, 1, -2, 28, 1368, -1, "Polar Express Caboose", 1); // 58
            AddComplexComponent(this, 1981, 1, -1, 28, 1368, -1, "Polar Express Caboose", 1); // 59
            AddComplexComponent(this, 1981, 1, 0, 28, 1368, -1, "Polar Express Caboose", 1); // 60
            AddComplexComponent(this, 1981, 1, 1, 28, 1368, -1, "Polar Express Caboose", 1); // 61
            AddComplexComponent(this, 1981, 1, 2, 28, 1368, -1, "Polar Express Caboose", 1); // 62
            AddComplexComponent(this, 11544, 1, 1, 30, 33, -1, "Polar Express Caboose", 1); // 63
            AddComplexComponent(this, 11580, -2, 0, 30, 33, -1, "Polar Express Caboose", 1); // 64
            AddComplexComponent(this, 11580, -2, -1, 30, 33, -1, "Polar Express Caboose", 1); // 65
            AddComplexComponent(this, 11580, 1, -1, 30, 33, -1, "Polar Express Caboose", 1); // 66
            AddComplexComponent(this, 11581, -1, -2, 30, 33, -1, "Polar Express Caboose", 1); // 67
            AddComplexComponent(this, 11581, 0, 1, 30, 33, -1, "Polar Express Caboose", 1); // 68
            AddComplexComponent(this, 11581, -1, 1, 30, 33, -1, "Polar Express Caboose", 1); // 69
            AddComplexComponent(this, 11581, 0, -2, 30, 33, -1, "Polar Express Caboose", 1); // 70
            AddComplexComponent(this, 11581, 1, -2, 30, 33, -1, "Polar Express Caboose", 1); // 71
            AddComplexComponent(this, 11547, -2, -2, 30, 33, -1, "Polar Express Caboose", 1); // 72
            AddComplexComponent(this, 11580, 1, 0, 30, 33, -1, "Polar Express Caboose", 1); // 73
            AddComplexComponent(this, 11580, -2, 1, 30, 33, -1, "Polar Express Caboose", 1); // 74
            AddComplexComponent(this, 11544, 1, 1, 35, 33, -1, "Polar Express Caboose", 1); // 75
            AddComplexComponent(this, 11580, 1, -1, 36, 33, -1, "Polar Express Caboose", 1); // 76
            AddComplexComponent(this, 11581, 1, -2, 35, 33, -1, "Polar Express Caboose", 1); // 77
            AddComplexComponent(this, 11581, -1, 1, 35, 33, -1, "Polar Express Caboose", 1); // 78
            AddComplexComponent(this, 11580, -2, 1, 35, 33, -1, "Polar Express Caboose", 1); // 79
            AddComplexComponent(this, 11581, -1, -2, 35, 33, -1, "Polar Express Caboose", 1); // 80
            AddComplexComponent(this, 11547, -2, -2, 35, 33, -1, "Polar Express Caboose", 1); // 81
            AddComplexComponent(this, 11580, -2, -1, 35, 33, -1, "Polar Express Caboose", 1); // 82
            AddComplexComponent(this, 1371, 1, 1, 41, 1107, -1, "Polar Express Caboose", 1); // 83
            AddComplexComponent(this, 1371, 1, 0, 41, 1107, -1, "Polar Express Caboose", 1); // 84
            AddComplexComponent(this, 1371, 1, -1, 41, 1107, -1, "Polar Express Caboose", 1); // 85
            AddComplexComponent(this, 1371, 0, 1, 41, 1107, -1, "Polar Express Caboose", 1); // 86
            AddComplexComponent(this, 1371, -1, 1, 41, 1107, -1, "Polar Express Caboose", 1); // 87
            AddComplexComponent(this, 1371, -1, 0, 41, 1107, -1, "Polar Express Caboose", 1); // 88
            AddComplexComponent(this, 1371, -1, -1, 41, 1107, -1, "Polar Express Caboose", 1); // 89
            AddComplexComponent(this, 1371, 0, -1, 41, 1107, -1, "Polar Express Caboose", 1); // 90
            AddComplexComponent(this, 1371, 0, 0, 41, 1107, -1, "Polar Express Caboose", 1); // 91
            AddComplexComponent(this, 6080, 1, 0, 30, 1260, -1, "Polar Express Caboose", 1); // 92
            AddComplexComponent(this, 6080, 0, 1, 30, 1260, -1, "Polar Express Caboose", 1); // 93
            AddComplexComponent(this, 6080, -1, 1, 30, 1260, -1, "Polar Express Caboose", 1); // 94
            AddComplexComponent(this, 893, 2, 2, 33, 1153, -1, "Polar Express Caboose", 1); // 95
            AddComplexComponent(this, 893, 2, 1, 33, 1153, -1, "Polar Express Caboose", 1); // 96
            AddComplexComponent(this, 893, 2, 0, 33, 1153, -1, "Polar Express Caboose", 1); // 97
            AddComplexComponent(this, 892, 2, 2, 33, 1153, -1, "Polar Express Caboose", 1); // 98
            AddComplexComponent(this, 892, 1, 2, 33, 1153, -1, "Polar Express Caboose", 1); // 99
            AddComplexComponent(this, 892, 0, 2, 33, 1153, -1, "Polar Express Caboose", 1); // 100
            AddComplexComponent(this, 892, 2, -1, 33, 1153, -1, "Polar Express Caboose", 1); // 101
            AddComplexComponent(this, 892, 1, -1, 33, 1153, -1, "Polar Express Caboose", 1); // 102
            AddComplexComponent(this, 892, 0, -1, 33, 1153, -1, "Polar Express Caboose", 1); // 103
            AddComplexComponent(this, 893, -1, 2, 33, 1153, -1, "Polar Express Caboose", 1); // 104
            AddComplexComponent(this, 893, 0, 2, 44, 1153, -1, "Polar Express Caboose", 1); // 105
            AddComplexComponent(this, 893, 0, 1, 44, 1153, -1, "Polar Express Caboose", 1); // 106
            AddComplexComponent(this, 892, 1, -2, 33, 1153, -1, "Polar Express Caboose", 1); // 107
            AddComplexComponent(this, 892, 2, -2, 33, 1153, -1, "Polar Express Caboose", 1); // 108
            AddComplexComponent(this, 6080, 1, -1, 30, 1260, -1, "Polar Express Caboose", 1); // 109
            AddComplexComponent(this, 6080, 1, 1, 30, 1260, -1, "Polar Express Caboose", 1); // 110
            AddComplexComponent(this, 6080, -1, 0, 30, 1260, -1, "Polar Express Caboose", 1); // 111
            AddComplexComponent(this, 6080, -1, -1, 30, 1260, -1, "Polar Express Caboose", 1); // 112
            AddComplexComponent(this, 6080, 0, -1, 30, 1260, -1, "Polar Express Caboose", 1); // 113
            AddComplexComponent(this, 6080, 0, 0, 30, 1260, -1, "Polar Express Caboose", 1); // 114
            AddComplexComponent(this, 6087, -1, -3, 30, 0, -1, "Polar Express Caboose", 1); // 115
            AddComplexComponent(this, 6088, 1, -3, 30, 0, -1, "Polar Express Caboose", 1); // 116
            AddComplexComponent(this, 6093, 1, 0, 42, 0, -1, "Polar Express Caboose", 1); // 117
            AddComplexComponent(this, 6094, -1, 1, 42, 0, -1, "Polar Express Caboose", 1); // 118
            AddComplexComponent(this, 6094, 0, -3, 30, 0, -1, "Polar Express Caboose", 1); // 119
            AddComplexComponent(this, 4651, 0, 2, 30, 1153, -1, "Polar Express Caboose", 1); // 120
            AddComplexComponent(this, 4652, 0, -3, 30, 1153, -1, "Polar Express Caboose", 1); // 121
            AddComplexComponent(this, 4652, 0, 0, 42, 1153, -1, "Polar Express Caboose", 1); // 122
            AddComplexComponent(this, 4654, 1, 1, 42, 1153, -1, "Polar Express Caboose", 1); // 123
            AddComplexComponent(this, 7370, 1, -1, 42, 1153, -1, "Polar Express Caboose", 1); // 124
            AddComplexComponent(this, 7371, -1, -1, 42, 1153, -1, "Polar Express Caboose", 1); // 125
            AddComplexComponent(this, 7371, -1, 2, 30, 1153, -1, "Polar Express Caboose", 1); // 126
            AddComplexComponent(this, 2038, 1, 2, 28, 1153, -1, "Polar Express Caboose", 1); // 127
            AddComplexComponent(this, 2039, -1, 2, 28, 1153, -1, "Polar Express Caboose", 1); // 128
            AddComplexComponent(this, 3024, 2, -1, 5, 1260, -1, "Polar Express Caboose", 1); // 129
            AddComplexComponent(this, 2905, -1, 2, 8, 1368, -1, "", 1); // 130
            AddComplexComponent(this, 7807, -1, 1, 8, 1153, -1, "", 1); // 131
            AddComplexComponent(this, 2903, -1, 0, 8, 1368, -1, "Polar Express Cargo Train", 1); // 132
            AddComplexComponent(this, 2903, -1, -3, 8, 1368, -1, "Polar Express Cargo Train", 1); // 133
            AddComplexComponent(this, 7807, -1, -2, 8, 1153, -1, "", 1); // 134
            AddComplexComponent(this, 2905, -1, -1, 8, 1368, -1, "", 1); // 135
            AddComplexComponent(this, 2594, 1, -5, 11, 1153, 1, "", 1); // 139
            AddComplexComponent(this, 5718, 2, 3, 7, 1102, -1, "Polar Express Caboose", 1); // 140
            AddComplexComponent(this, 5722, -2, 3, 6, 1102, -1, "Polar Express Caboose", 1); // 141
            AddComplexComponent(this, 1981, -1, 3, 6, 1108, -1, "Polar Express Caboose", 1); // 142
            AddComplexComponent(this, 1981, 1, 3, 6, 1108, -1, "Polar Express Caboose", 1); // 143
            AddComplexComponent(this, 1981, 0, 3, 6, 1108, -1, "Polar Express Caboose", 1); // 144
            AddComplexComponent(this, 11546, 1, 3, 8, 33, -1, "Polar Express Caboose", 1); // 145
            AddComplexComponent(this, 11584, -2, 3, 8, 33, -1, "Polar Express Caboose", 1); // 146
            AddComplexComponent(this, 11585, -1, 3, 8, 33, -1, "Polar Express Caboose", 1); // 147
            AddComplexComponent(this, 1981, 0, 4, 6, 1108, -1, "Polar Express Caboose", 1); // 148
            AddComplexComponent(this, 1981, 1, 4, 6, 1108, -1, "Polar Express Caboose", 1); // 149
            AddComplexComponent(this, 1981, -1, 4, 6, 1108, -1, "Polar Express Caboose", 1); // 150
            AddComplexComponent(this, 2144, -1, 5, 8, 33, -1, "Polar Express Caboose", 1); // 151
            AddComplexComponent(this, 2144, 0, 5, 8, 33, -1, "Polar Express Caboose", 1); // 152
            AddComplexComponent(this, 2144, 1, 5, 8, 33, -1, "Polar Express Caboose", 1); // 153
            AddComplexComponent(this, 2145, 1, 4, 8, 33, -1, "Polar Express Caboose", 1); // 154
            AddComplexComponent(this, 2145, -2, 4, 8, 33, -1, "Polar Express Caboose", 1); // 155
            AddComplexComponent(this, 2143, 1, 5, 8, 33, -1, "Polar Express Caboose", 1); // 156
            AddComplexComponent(this, 2143, -2, 5, 8, 33, -1, "Polar Express Caboose", 1); // 157
            AddComplexComponent(this, 1981, 1, 3, 28, 1368, -1, "Polar Express Caboose", 1); // 158
            AddComplexComponent(this, 1981, -1, 3, 28, 1368, -1, "Polar Express Caboose", 1); // 159
            AddComplexComponent(this, 1981, 0, 3, 28, 1368, -1, "Polar Express Caboose", 1); // 160
            AddComplexComponent(this, 7883, 0, 6, 7, 1109, -1, "Polar Express Caboose", 1); // 161
            AddComplexComponent(this, 6085, 1, 3, 29, 0, -1, "Polar Express Caboose", 1); // 162
            AddComplexComponent(this, 6086, -1, 3, 30, 0, -1, "Polar Express Caboose", 1); // 163
            AddComplexComponent(this, 6093, 1, 3, 30, 0, -1, "Polar Express Caboose", 1); // 164
            AddComplexComponent(this, 12255, -1, 4, 8, 1153, -1, "Polar Express Caboose", 1); // 165
            AddComplexComponent(this, 1981, 1, 5, 6, 1108, -1, "Polar Express Caboose", 1); // 166
            AddComplexComponent(this, 1981, 0, 5, 6, 1108, -1, "Polar Express Caboose", 1); // 167
            AddComplexComponent(this, 1981, -1, 5, 6, 1108, -1, "Polar Express Caboose", 1); // 168
            AddComplexComponent(this, 2145, -2, 5, 8, 33, -1, "Polar Express Caboose", 1); // 169
            AddComplexComponent(this, 2145, 1, 5, 8, 33, -1, "Polar Express Caboose", 1); // 170
            AddComplexComponent(this, 2038, 1, 3, 28, 1153, -1, "Polar Express Caboose", 1); // 171
            AddComplexComponent(this, 2066, 1, 3, 28, 1153, -1, "Polar Express Caboose", 1); // 172
            AddComplexComponent(this, 2594, 1, 5, 11, 1153, 1, "", 1); // 174
            AddComplexComponent(this, 2594, -2, 5, 11, 1153, 1, "", 1); // 175
            AddComplexComponent(this, 892, 3, -2, 33, 1153, -1, "Polar Express Caboose", 1); // 176
            AddComplexComponent(this, 6276, 3, 2, 10, 2101, -1, "Polar Express Caboose", 1); // 177
            AddComplexComponent(this, 6276, 3, -1, 10, 2101, -1, "Polar Express Caboose", 1); // 178
            AddComplexComponent(this, 6276, 3, -2, 10, 2101, -1, "Polar Express Caboose", 1); // 179
            AddComplexComponent(this, 4269, 3, -1, 0, 2101, -1, "Polar Express Caboose", 1); // 180
            AddComplexComponent(this, 4269, 3, -2, 0, 2101, -1, "Polar Express Caboose", 1); // 181
            AddComplexComponent(this, 4269, 3, 2, 0, 2101, -1, "Polar Express Caboose", 1); // 182
            AddComplexComponent(this, 893, 3, 0, 21, 1153, -1, "Polar Express Caboose", 1); // 183
            AddComplexComponent(this, 6276, 3, 3, 10, 2101, -1, "Polar Express Caboose", 1); // 184
            AddComplexComponent(this, 4269, 3, 3, 0, 2101, -1, "Polar Express Caboose", 1); // 185
            AddComplexComponent(this, 893, 3, 4, 21, 1153, -1, "Polar Express Caboose", 1); // 186
            AddComplexComponent(this, 9005, 3, 4, 18, 38, -1, "", 1); // 187
        }

        public PolarExpressCabooseAddon(Serial serial) : base(serial)
        {}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset,
            int hue, int lightsource, string name = null, int amount = 1)
        {
            AddonComponent ac = new AddonComponent(item);
            if (!string.IsNullOrEmpty(name))
            {
                ac.Name = name;
            }
            if (hue != 0)
            {
                ac.Hue = hue;
            }
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
            {
                ac.Light = (LightType) lightsource;
            }
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write(0); // Version
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    public class PolarExpressCabooseAddonDeed : BaseAddonDeed
    {
        public override BaseAddon Addon { get { return new PolarExpressCabooseAddon(); } }

        [Constructable]
        public PolarExpressCabooseAddonDeed()
        {
            Name = "PolarExpressCaboose";
        }

        public PolarExpressCabooseAddonDeed(Serial serial) : base(serial)
        {}

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write(0); // Version
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }
}