////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////

namespace Server.Items
{
    public class TableSawAddon : BaseAddon
    {
        public override BaseAddonDeed Deed { get { return new TableSawAddonDeed(); } }

        [Constructable]
        public TableSawAddon()
        {
            AddComplexComponent((BaseAddon) this, 10266, 0, 0, 3, 1836, -1, "Table", 1); // 1
            AddComplexComponent((BaseAddon) this, 4528, 1, 1, 13, 1900, -1, "TableSaw Blade", 1); // 2
            AddComplexComponent((BaseAddon) this, 7127, 1, 0, 13, 2006, -1, "Guard", 1); // 3
            AddComplexComponent((BaseAddon) this, 4239, 0, 0, 6, 0, -1, "A switch", 1); // 4
            AddComplexComponent((BaseAddon) this, 1801, 0, 0, 0, 1836, -1, "", 1); // 5
            AddComplexComponent((BaseAddon) this, 4239, 1, 0, 2, 1900, -1, "A switch", 1); // 6
        }

        public TableSawAddon(Serial serial) : base(serial)
        {}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset,
            int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset,
            int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
            {
                ac.Name = name;
            }
            if (hue != 0)
            {
                ac.Hue = hue;
            }
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
            {
                ac.Light = (LightType) lightsource;
            }
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write(0); // Version
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    public class TableSawAddonDeed : BaseAddonDeed
    {
        public override BaseAddon Addon { get { return new TableSawAddon(); } }

        [Constructable]
        public TableSawAddonDeed()
        {
            Name = "TableSaw";
        }

        public TableSawAddonDeed(Serial serial) : base(serial)
        {}

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write(0); // Version
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }
}